### PR TITLE
Update en_US.json

### PR DESCRIPTION
**Pull request by beolse**
Hello,
- I have translated the language pack from English to Russian, 
- after I added the translation file to the folder with the program `"...\AppData\Local\Programs\SiYuan\resources\appearance\lang\ru_RU.json"`
- on the Settings /Appearance/Language selection the file is selected, the translation is correct
- now the interface speaks Russian
- the problem is that Notebooks in the Document Tree do not work:
	- the list does not open, you cannot select notes,
		- I wrote in more detail in the topic https://github.com/siyuan-note/siyuan/issues/10209
	- I do not know the reason  
- at your request, I am sending a PR to your _en_US.json_
- consider extending the language packs to the program,

* [ ] Please commit to the dev branch
* [ ] For contributing new features, please supplement and improve the corresponding user guide documents
* [ ] For bug fixes, please describe the problem and solution via code comments
* [ ] For text improvements (such as typos and wording adjustments), please submit directly

### CODE REVIEW

**Comment by 88250** [comment]
Please create a new file ru_RU.json.

**Comment by zxhd863943427** [comment]
Wait, I seem to have observed the wrong point before, you mean you can't expand the document in the document tree after using RU translation?

**Comment by OlZin** [comment]
> Please create a new file ru_RU.json.

I have attached the file in this message
https://github.com/siyuan-note/siyuan/issues/10209#issuecomment-1898494721

**Comment by 88250** [comment]
> ru_RU.json

Hello, please create and commit the ru_RU.json file, and do not modify en_US.json, otherwise we will not be able to merge this PR.

**Comment by 88250** [comment]
It has been on hold for too long, so we have closed it first. If it is convenient, please PR again if it is convenient. Thank you.

**Pull request closed without merging**
